### ISSUE TITLE
GraphQL/Wagtail Rebuild trigger

### ISSUE THREAD

**Issue by IAmNatch** [torchbox/torchbox-frontend#114]
This is a great example of bring Gatsby and Wagtail together to create an amazing headless system.

I'm wondering how you triggered builds of Gatsby as the data is updated in wagtail.

Thanks a lot!

**Comment by zerolab** [comment]
Hey @IAmNatch,

we've now moved to a traditional setup for the Torchbox website, however you can have a look at https://github.com/torchbox/wagtail-torchbox/tree/29db488bdd2a611b2e4be35868acb56c726f5348/tbx/netlify for how this was done. 

tl;dr -- manual deployment triggerring
