### ISSUE TITLE
Team page in reverse order in Firefox

### ISSUE THREAD

**Issue by nicklee** [torchbox/torchbox-frontend#122]
No idea why this is happening but the order of people on the team page is reversed when browsing in Firefox:

https://torchbox.com/team/

Surnames are Z-A instead of A-Z (like in other browsers).

**Comment by nicklee** [comment]
![Screenshot 2020-08-06 at 16 18 32](https://user-images.githubusercontent.com/298766/89549668-85866b00-d800-11ea-82dc-97672adf4655.png)
![Screenshot 2020-08-06 at 16 18 34](https://user-images.githubusercontent.com/298766/89549759-a51d9380-d800-11ea-8206-cdeb2d3c483b.png)

**Comment by nicklee** [comment]
Potentially something to do with this:
https://github.com/torchbox/torchbox-frontend/blob/master/src/templates/team/team-listing.js#L18

**Comment by balazs-endresz** [comment]
This happens only in firefox:

```
a = [1,2,3]
Array(3) [ 1, 2, 3 ]

a.sort(e => 1)
Array(3) [ 3, 2, 1 ]

a.sort(e => 1)
Array(3) [ 1, 2, 3 ]

a.sort(e => 1)
Array(3) [ 3, 2, 1 ]
```

But it's stable if you reference an outside variable: `a.sort(e => window, 1)`.

**Comment by balazs-endresz** [comment]
> But it's stable if you reference an outside variable: a.sort(e => window, 1).

Ah, I meant `a.sort(e => { window; return 1})` but that doesn't actually help. 

Still, weird how `a.sort(e => 1)` changes.

**Comment by balazs-endresz** [comment]
https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#compare-T-T-

> The implementor must ensure that sgn(compare(x, y)) == -sgn(compare(y, x)) for all x and y.

Maybe this is required for javascript too. And that's likely not satisfied here: https://github.com/torchbox/torchbox-frontend/blob/master/src/templates/team/team-listing.js#L35

**Comment by balazs-endresz** [comment]
For some reason I thought it wouldn't really matter in this case with the booleans but it is still important to return zero when the two items being compared are the same: `.sort((p1, p2) => (p1.isSenior === p2.isSenior ? 0 : p1.isSenior ? 1 : -1 ))`. If you don't do that then items will be mixed up differently depending on what specific algorithm each browser uses for the sorting.
